//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajanvarausprojekti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayttajatunnukset
    {
        public int kayttajatunnus_id { get; set; }
        public string kayttajatunnus { get; set; }
        public string salasana { get; set; }
        public int opettaja_id { get; set; }
        public int oikeudet_id { get; set; }
    
        public virtual Yllapitooikeudet Yllapitooikeudet { get; set; }
        public virtual Opettajat Opettajat { get; set; }
    }
}
