//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ajanvarausprojekti.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Palautteet
    {
        public int palaute_id { get; set; }

        [DataType(DataType.MultilineText)]
        public string palaute { get; set; }
        public System.DateTime palaute_pvm { get; set; }
        public Nullable<int> palautetyyppi_id { get; set; }
        public int opettaja_id { get; set; }
    
        public virtual Opettajat Opettajat { get; set; }
        public virtual Palautetyypit Palautetyypit { get; set; }

    }
}
